export const  GET_WINDOW_SIZE = 'GET_WINDOW_SIZE';

export const SHOW_KEYBOARD = 'SHOW_KEYBOARD';


export const FETCH_RECORDS = 'FETCH_RECORDS';
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';
export const FETCH_RECORDS_FAIL = 'FETCH_RECORDS_FAIL';
